# Generated by Django 3.1.3 on 2020-11-10 07:59

from django.db import migrations, models
import servers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('host', models.CharField(max_length=250, unique=True)),
                ('install', models.CharField(choices=[('new', 'New server without nothing'), ('docker', 'Only Docker installed'), ('api', 'Running Docker server with enabled API')], max_length=250)),
                ('date_created', models.DateTimeField(default=servers.models.now)),
                ('date_updated', models.DateTimeField(default=servers.models.now)),
                ('status', models.BooleanField(default=False)),
                ('SSH_username', models.CharField(blank=True, default='root', max_length=250, null=True)),
                ('SSH_password', models.CharField(blank=True, max_length=250, null=True)),
                ('SSH_port', models.PositiveIntegerField(blank=True, default=22, null=True)),
                ('api_port', models.PositiveIntegerField(blank=True, default=2375, null=True)),
                ('Server_ID', models.CharField(blank=True, max_length=250, null=True)),
                ('Containers', models.CharField(blank=True, max_length=250, null=True)),
                ('ContainersRunning', models.CharField(blank=True, max_length=250, null=True)),
                ('ContainersPaused', models.CharField(blank=True, max_length=250, null=True)),
                ('ContainersStopped', models.CharField(blank=True, max_length=250, null=True)),
                ('Images', models.CharField(blank=True, max_length=250, null=True)),
                ('KernelVersion', models.CharField(blank=True, max_length=250, null=True)),
                ('OperatingSystem', models.CharField(blank=True, max_length=250, null=True)),
                ('OSType', models.CharField(blank=True, max_length=250, null=True)),
                ('Architecture', models.CharField(blank=True, max_length=250, null=True)),
                ('MemTotal', models.CharField(blank=True, max_length=250, null=True)),
                ('HostName', models.CharField(blank=True, max_length=250, null=True)),
                ('ServerVersion', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
