# Generated by Django 3.1.3 on 2020-11-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='Server_ID',
            new_name='Server_id',
        ),
    ]
